language: ruby
rvm:
  - 2.3.1
env:
  - "NODE_VERSION=6.5.0"

services:
  - postgresql

bundler_args: "--without development --deployment"

cache: bundler

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
  - source ~/.nvm/nvm.sh && npm install

script:
  - bundle exec rspec
  - source ~/.nvm/nvm.sh && npm run test